2021/03/30 18:12:15 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /api/notification/find/?&@select=id,status,isRequest,createTimestamp,message,approveUrl,request.{permissionTo.{approve,reject},requesterUser}&user=eq(@me)&@ORDER=createTimestamp%20DESC HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost:8080", referrer: "http://localhost:8080/agentes/edita/25/"
2021/03/30 18:13:15 [error] 8#8: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /api/notification/find/?&@select=id,status,isRequest,createTimestamp,message,approveUrl,request.{permissionTo.{approve,reject},requesterUser}&user=eq(@me)&@ORDER=createTimestamp%20DESC HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost:8080", referrer: "http://localhost:8080/agentes/edita/25/"
2021/03/31 08:10:17 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost:8080"
2021/03/31 08:10:31 [error] 8#8: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost:8080"
2021/03/31 08:10:33 [error] 8#8: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost:8080"
2021/03/31 08:10:33 [error] 8#8: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost:8080"
